subdir-ccflags-y := \
    -fdata-sections -ffunction-sections -finline-functions -ftree-vectorize -funroll-loops

obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208) += goodix/
obj-$(CONFIG_FINGERPRINT_FPC1020) += fpc/
